workspace:
  path: src/github.com/scireum/sirius-db/${DRONE_MACHINE}/${DRONE_BUILD_NUMBER}
clone:
  git:
    image: plugins/git
    volumes:
    - /var/repos/scireum/siriusdb:/drone/src/github.com/scireum/sirius-db
pipeline:
  test:
    image: scireum/sirius-build
    commands:
      - env
      - mvn clean test -U -Dbuild.number=${DRONE_BUILD_NUMBER} -Dbuild.vcs.number=${DRONE_COMMIT}
    volumes:
      - /root/.m2:/root/.m2
      - /root/.gnupg:/root/.gnupg
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/repos/scireum/siriusdb:/drone/src/github.com/scireum/sirius-db
  deploy:
    image: scireum/sirius-build
    commands:
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.projectKey=sirius-db -U -Dbuild.number=${DRONE_BUILD_NUMBER} -Dbuild.vcs.number=${DRONE_COMMIT}
    volumes:
      - /root/.m2:/root/.m2
      - /root/.gnupg:/root/.gnupg
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/repos/scireum/siriusdb:/drone/src/github.com/scireum/sirius-db
    when:
      branch: [ master, feature/* ]
      event: push
