pipeline:
  test:
    image: scireum/sirius-build
    commands:
      - mvn -DDOCKER_HOST=tcp://192.168.192.178:2376 clean test
    volumes:
      - /root/.m2:/root/.m2
      - /root/.gnupg:/root/.gnupg
      - /var/run/docker.sock:/var/run/docker.sock
  deploy:
    image: scireum/sirius-build
    commands:
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.projectKey=sirius-db -U
    volumes:
      - /root/.m2:/root/.m2
      - /root/.gnupg:/root/.gnupg
    when:
      branch: [ master, feature/* ]  
